config {
  type: "table", // Creates a table in BigQuery. 
  schema: "staging",
  description: "Aggregated table with sum of sessions and users per year"
}

js {
    const startDate = new Date();
}

-- Use the ref() function to manage dependencies.
-- Learn more about ref() and other built in functions here: https://cloud.google.com/dataform/docs/dataform-core

SELECT 
ga_year as year,
sum(ga_sessions) as sessions, 
sum(ga_users) as users, 

from ${ref("first_view")}

group by year
